# Generated by Django 4.1 on 2022-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiveTitle', models.CharField(max_length=200)),
                ('aciveFile', models.FileField(upload_to='achivements')),
                ('achiveUrl', models.URLField()),
                ('achiveDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('designation', models.CharField(choices=[('Director', 'Director'), ('Director in Charge', 'Director in Charge'), ('Dy Director', 'Dy Director')], max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=200)),
                ('cv', models.FileField(upload_to='director/cv')),
                ('image', models.ImageField(upload_to='director/profile')),
                ('joinedOn', models.DateTimeField()),
                ('about', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EBSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=254)),
                ('facultyQualification', models.CharField(max_length=254)),
                ('facultyPhone', models.CharField(max_length=254)),
                ('facutyDesignation', models.CharField(choices=[('Director', 'Director'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=100)),
                ('facultyCV', models.FileField(upload_to='faculty/cv')),
                ('facultyImage', models.ImageField(upload_to='faculty/image')),
            ],
        ),
        migrations.CreateModel(
            name='FlashNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=254)),
                ('newsLink', models.URLField(blank=True, null=True)),
                ('newsFile', models.FileField(blank=True, null=True, upload_to='news')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='datetime')),
                ('newsImg', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altTitle', models.CharField(max_length=254, null=True)),
                ('logoUrl', models.URLField(max_length=254, null=True)),
                ('logImg', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NIRFCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=254)),
                ('file', models.FileField(blank=True, upload_to='noticeboard')),
                ('noticeUrl', models.URLField(blank=True, max_length=254, null=True)),
                ('noticedate', models.DateTimeField(blank=True, null=True, verbose_name='datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGriveance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderTitle', models.CharField(max_length=254)),
                ('tenderFile', models.FileField(upload_to='tender')),
                ('tenderLastDate', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
        migrations.CreateModel(
            name='TranninPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VegilanceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
