# Generated by Django 4.1 on 2022-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BWC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=200)),
                ('joinedOn', models.DateTimeField()),
                ('designation', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Ex-Officio - Secretary', 'Ex-Officio - Secretary'), ('Member', 'Member')], max_length=100)),
            ],
        ),
    ]
