# Generated by Django 4.1 on 2022-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashnews',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='datetime'),
        ),
    ]
