# Generated by Django 4.1 on 2022-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0003_alter_flashnews_date_alter_flashnews_newsfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashnews',
            name='newsImg',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
