# Generated by Django 4.1 on 2022-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0004_flashnews_newsimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altTitle', models.CharField(max_length=254, null=True)),
                ('logoUrl', models.URLField(max_length=254, null=True)),
                ('logImg', models.ImageField(upload_to='logos')),
            ],
        ),
    ]
