# Generated by Django 4.1 on 2022-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0005_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=254)),
                ('file', models.ImageField(upload_to='noticeboard')),
                ('noticeUrl', models.URLField(max_length=254, null=True)),
                ('noticedate', models.DateTimeField(blank=True, null=True, verbose_name='datetime')),
            ],
        ),
    ]
