# Generated by Django 4.1 on 2022-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0006_noticeboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='file',
            field=models.ImageField(blank=True, upload_to='noticeboard'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='noticeUrl',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
