# Generated by Django 4.1 on 2022-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0007_alter_noticeboard_file_alter_noticeboard_noticeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='file',
            field=models.FileField(blank=True, upload_to='noticeboard'),
        ),
    ]
