# Generated by Django 4.1 on 2022-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0008_alter_noticeboard_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=254)),
                ('facultyQualification', models.CharField(max_length=254)),
                ('facultyPhone', models.CharField(max_length=254)),
                ('facutyDesignation', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('facultyCV', models.FileField(upload_to='faculty/cv')),
                ('facultyImage', models.ImageField(upload_to='faculty/image')),
            ],
        ),
    ]
