# Generated by Django 4.1 on 2022-08-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0009_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facutyDesignation',
            field=models.CharField(choices=[('D', 'Director'), ('P', 'Professor'), ('AS', 'Associate Professor'), ('AP', 'Assistant Professor')], max_length=10),
        ),
    ]
