# Generated by Django 4.1 on 2022-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0010_alter_faculty_facutydesignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facutyDesignation',
            field=models.CharField(choices=[('Director', 'Director'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=100),
        ),
    ]
