# Generated by Django 4.1 on 2022-08-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0011_alter_faculty_facutydesignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderTitle', models.CharField(max_length=254)),
                ('tenderFile', models.FileField(upload_to='tender')),
                ('tenderLastDate', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
    ]
