# Generated by Django 4.1 on 2022-08-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsnews',
            name='file',
            field=models.FileField(null=True, upload_to='anews'),
        ),
    ]
