# Generated by Django 4.1 on 2022-08-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
